server:
  port: 8080
# 数据库连接
#spring:
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3306/kongv0.1?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
#    password: root
#    username: root

# mybatis
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  type-aliases-package: fs.luke.kong.modules.**.entity
  mapper-locations: classpath:fs/kong/modules/**/mapper/*Mapper.xml
  type-aliases-super-type: fs.luke.kong.core.entity.BaseEntity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


# pagehelper
#pagehelper:
#  helper-dialect: mysql
#  reasonable: true
#  support-methods-arguments: true
#  params: countSql